import './globals.css'
import localFont from 'next/font/local'
import { ClerkProvider } from '@clerk/nextjs'

const netflixFont = localFont({
  src: [
    {
      path: '../fonts/NetflixSans-Light.woff2',
      weight: '300',
      style: 'normal',
    },
    {
      path: '../fonts/NetflixSans-Regular.woff2',
      weight: '400',
      style: 'normal',
    },
    {
      path: '../fonts/NetflixSans-Medium.woff2',
      weight: '500',
      style: 'normal',
    },
    {
      path: '../fonts/NetflixSans-Bold.woff2',
      weight: '700',
      style: 'normal',
    },
  ]
})

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  
  return (
    <html lang="en">
      <body className={netflixFont.className}>{children}</body>
    </html>
  )
}
